version: "3.9"
services:
  ### Prefect Database
  database:
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=prefect_hands_on;
    ports:
      - 5432:5432
    volumes:
      - db:/data/postgresql/data
    profiles: ["orion"]

  ### Prefect Orion(Server) API
  orion:
    image: prefect:latest
    restart: always
    volumes:
      - prefect:/root/.prefect
    entrypoint: ["prefect", "server", "start"]
    environment:
      - PREFECT_SERVER_API_HOST=0.0.0.0
      - PREFECT_API_DATABASE_CONNECTION_URL=postgresql+asyncpg://postgres:postgres@database:5432/prefect_hands_on
      - PREFECT_API_URL=http://localhost:4300/api
    ports:
      - 4300:4200
    depends_on:
      - database
    profiles: ["orion"]
    build:
      context: .
      args:
        ENVIRONMENT: dev

  ## Prefect Agent
  agent:
    image: prefect:latest
    restart: always
    entrypoint: ["prefect", "agent", "start", "-q", "default"]
    volumes:
      - ".:/app"
    environment:
      - PREFECT_API_URL=http://orion:4200/api
    ports:
      - 8786:8787
    profiles: ["agent"]
    build:
      context: .
      args:
        ENVIRONMENT: dev

  ### Prefect CLI
  cli:
    image: prefect:latest
    entrypoint: "bash"
    volumes:
      - ".:/app"
    environment:
      - PREFECT_API_URL=http://orion:4200/api
    profiles: ["cli"]
    build:
      context: .
      args:
        ENVIRONMENT: dev

volumes:
  prefect:
  db:
networks:
  default:
    name: prefect-hands_on